# Flat Support Fund Account Book method can be used:

Github: Maximum number of imports supported by 4 GitHub Kisuke nicknames like # [Leader1, Advocate2].
patreon: #get your Patreon nickname
Public Group: Set the public group nickname#
ko_fi: #Ko-fi The nickname requested for import
Tidal unloader: #imported tidal unloader/package name (e.g. npm/babel)
Social Bridges: A single social bridge project (e.g. #cloudfoundry) was imported.
liberapay: #nickname for freepay request import
Explore SO: #PrimaryIExplore SO nickname for artificial uses
lfx_Crowdfunding: Integrated Search LFX Crowdfunding Project Name Name Portal Surface, Example #CloudCollectCapital.
Polar: Nickname for #polar importer
Purchased from me: #Purchased by importer Nickname
Thank you very much for your question: #Inquirer Thank you very much for your name change.
Self-edit: # Used to MAX set up the self-edit help network.
